### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by chbndrhnns** [rainmanwy/robotframework-ScapyLibrary#1]
Hey,

The example from your readme fails here with

```
[ ERROR ] Error in file '/Users/jo/dev/master/robot/src/dc-wordpress/tests/dc-wordpress.robot': Initializing test library 'ScapyLibrary' with no arguments failed: TypeError: unsupported operand type(s) for +: 'member_descriptor' and 'str'
Traceback (most recent call last):
  File "/Users/jo/.virtualenvs/robot/lib/python2.7/site-packages/ScapyLibrary/__init__.py", line 20, in __init__
    _base.__init__(self)
  File "/Users/jo/.virtualenvs/robot/lib/python2.7/site-packages/ScapyLibrary/keywords/layers.py", line 16, in __init__
    self._init_layers()
  File "/Users/jo/.virtualenvs/robot/lib/python2.7/site-packages/ScapyLibrary/keywords/layers.py", line 81, in _init_layers
    doc = protocol.name + '\n\n'
Tests.Dc-Wordpress
```

Can you please help me to fix it?

Bye,
Jo

**Comment by rainmanwy** [comment]
how about the scapy version you are using?

i may check this later!


获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chbndrhnns** [comment]
I am using scapy 2.3.3

**Comment by chbndrhnns** [comment]
Hey there,

Did you have any chance to take a look?

Bye,
jo

**Comment by rainmanwy** [comment]
sorry, i haven't local environment recently. I am check this this weekend.

And you may change the code yourself also. for example, use str() to convert it to string.

And check whether it works.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rainmanwy** [comment]
@chbndrhnns ,
I have committed the fix. you could have a try the latest version(from github). There are some errors that may report from scapy, i will check it later. right now i just ignore these errors.

Thank you very much!

**Comment by chbndrhnns** [comment]
Hey, 

I can run the simple example now. Thanks very much!

bye,
jo

**Comment by dingo10** [comment]
Could you please push changes to pip? 

ThankYou
dingo
