### ISSUE TITLE
[ERROR] Loading module scapy.layers.cansocket_python_can

### ISSUE THREAD

**Issue by marknefedov** [rainmanwy/robotframework-ScapyLibrary#11]
Hi, I've tried ICMP example this library with latest scapy on Rocky Linux 9.2 and got this
Python 3.9.16
Scapy 2.5.0
Robot Framework 6.1 (Python 3.9.16 on linux)

ScapyLibrary installed with `pip install robotframework-ScapyLibrary`
```
$ pip show robotframework-ScapyLibrary
Name: robotframework-ScapyLibrary
Version: 0.1.6
Summary: Scapy library for Robot Framework
Home-page: https://github.com/rainmanwy/robotframework-ScapyLibrary
Author: Wang Yang
Author-email: wang_yang1980@hotmail.com
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: scapy
Required-by: 
```

```
Error in file '/root/eupf/robot/EstablishSession.robot' on line 2: Initializing library 'ScapyLibrary' with no arguments failed: TypeError: can only concatenate tuple (not "str") to tuple
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ScapyLibrary/__init__.py", line 20, in __init__
    _base.__init__(self)
  File "/usr/local/lib/python3.9/site-packages/ScapyLibrary/keywords/layers.py", line 15, in __init__
    self._init_layers()
  File "/usr/local/lib/python3.9/site-packages/ScapyLibrary/keywords/layers.py", line 80, in _init_layers
    doc = protocol._name + '\n\n'
TypeError: can only concatenate tuple (not "str") to tuple
Loading module scapy.layers.cansocket_python_can
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/scapy/main.py", line 204, in load_contrib
    importlib.import_module("scapy.contrib." + name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/scapy/contrib/cansocket_python_can.py", line 29, in <module>
    from can import Message as can_Message
ModuleNotFoundError: No module named 'can'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/scapy/main.py", line 156, in _load
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scapy.layers.cansocket_python_can'
```

**Comment by marknefedov** [comment]
[log.zip](https://github.com/rainmanwy/robotframework-ScapyLibrary/files/11949246/log.zip)

**Comment by yeyuzhen** [comment]
@marknefedov  I encountered the same problem. Finally, I fixed the problem  by executing "pip3 install python-can" to install python-can package. This package contain "cansocket_python_can" module.
