### ISSUE TITLE
Failing with too many errors

### ISSUE THREAD

**Issue by sreeramr30** [rainmanwy/robotframework-ScapyLibrary#12]
python3 -m ScapyLibrary.layerDoc Scapy.html
WARNING: [bgp.py] use_2_bytes_asn: True
WARNING: CARP overwrites VRRP !
ERROR: Loading module scapy.layers.cansocket_python_can
Traceback (most recent call last):
  File "/home/midmarket/.local/lib/python3.10/site-packages/scapy/main.py", line 204, in load_contrib
    importlib.import_module("scapy.contrib." + name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/midmarket/.local/lib/python3.10/site-packages/scapy/contrib/cansocket_python_can.py", line 29, in <module>
    from can import Message as can_Message
ModuleNotFoundError: No module named 'can'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/midmarket/.local/lib/python3.10/site-packages/scapy/main.py", line 156, in _load
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'scapy.layers.cansocket_python_can'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/midmarket/.local/lib/python3.10/site-packages/ScapyLibrary/layerDoc.py", line 106
    print "Generate layer doc to %s" % os.path.abspath(docFile)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by sreeramr30** [comment]
I downloaded the latest robotframework-scapy library and ended with the above issues
