### ISSUE TITLE
AttributeError: 'module' object has no attribute "IE_Base"

### ISSUE THREAD

**Issue by dingo10** [rainmanwy/robotframework-ScapyLibrary#2]
Hi

I did pip install,
Now while importing I'm getting this error.  

>>> import ScapyLibrary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\ScapyLibrary\__init__.py", line 7, in <mod
ule>
    from ScapyLibrary.keywords.layers import LayersWrapper
  File "C:\Python27\lib\site-packages\ScapyLibrary\keywords\layers.py", line 8,
in <module>
    from ScapyLibrary.utils._scapy import scapylib
  File "C:\Python27\lib\site-packages\ScapyLibrary\utils\_scapy.py", line 31, in
 <module>
    scapylib.load_contrib(mod)
  File "C:\Python27\lib\site-packages\scapy\main.py", line 83, in load_contrib
    __import__("scapy.contrib." + name)
  File "C:\Python27\lib\site-packages\scapy\contrib\gtp_v2.py", line 120, in <mo
dule>
    class IE_IPv4(gtp.IE_Base):
AttributeError: 'module' object has no attribute 'IE_Base'
>>>

**Comment by dingo10** [comment]
It was my environment, resolved now.

**Comment by rainmanwy** [comment]
ok. If there are some other problem, you may clone this project and install it by source code.
pyppi version is not the latest version, may have some problems.

**Comment by rainmanwy** [comment]
@dingo10 , i have updated the version in pypi.
