### ISSUE TITLE
Importing test library 'ScapyLibrary' failed: ImportError: cannot import name NPCAP_PATH

### ISSUE THREAD

**Issue by jccaja** [rainmanwy/robotframework-ScapyLibrary#4]
Hello friend,

I tried to use the library, I installed it on py2.7 but ride does not recognize it, the RIDE log says:

`Importing test library 'ScapyLibrary' failed: ImportError: cannot import name NPCAP_PATH`

I also tried to run the example test without using ride and robot does not find the keywords, when I run it it says:

```
C:\Users\b.jccd>robot C:\Users\b.jccd\Documents\Programas\Robot\scapy.robot
[ WARN ] No pcap provider available ! pcap won't be used
[ WARN ] import scapy failed, please check whether scapy is installed
[ ERROR ] Error in file 'C:\Users\b.jccd\Documents\Programas\Robot\scapy.robot': Importing test library 'ScapyLibrary' failed: ImportError: cannot import name NPCAP_PATH
Traceback (most recent call last):
  File "c:\users\b.jccd\documents\programas\python\lib\site-packages\ScapyLibrary\__init__.py", line 7, in <module>
    from ScapyLibrary.keywords.layers import LayersWrapper
  File "c:\users\b.jccd\documents\programas\python\lib\site-packages\ScapyLibrary\keywords\layers.py", line 8, in <module>
    from ScapyLibrary.utils._scapy import scapylib
  File "c:\users\b.jccd\documents\programas\python\lib\site-packages\ScapyLibrary\utils\_scapy.py", line 35, in <module>
    raise err
PYTHONPATH:
  C:\Users\b.jccd\Documents\Programas\Python\Scripts\robot.exe
  C:\Windows\SYSTEM32\python27.zip
  c:\users\b.jccd\documents\programas\python\DLLs
  c:\users\b.jccd\documents\programas\python\lib
  c:\users\b.jccd\documents\programas\python\lib\plat-win
  c:\users\b.jccd\documents\programas\python\lib\lib-tk
  c:\users\b.jccd\documents\programas\python
  c:\users\b.jccd\documents\programas\python\lib\site-packages
  c:\users\b.jccd\documents\programas\python\lib\site-packages\win32
  c:\users\b.jccd\documents\programas\python\lib\site-packages\win32\lib
  c:\users\b.jccd\documents\programas\python\lib\site-packages\Pythonwin
==============================================================================
Scapy
==============================================================================
Send And Receive, Return Reply                                        | FAIL |
No keyword with name 'IP' found.
------------------------------------------------------------------------------
Scapy                                                                 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\b.jccd\output.xml
Log:     C:\Users\b.jccd\log.html
Report:  C:\Users\b.jccd\report.html
```

I installed on `c:\users\b.jccd\documents\programas\python\lib\site-packages`, I don't know why it doesn't find it
I don't know what to do, contact me for further information about this bug/error

Best Regards

**Comment by rainmanwy** [comment]
@jccaja , it is ok in my Linux env.
Could you have a try the latest version in pypi.
And if it is still not work, could you confirm that scapy is install correctly.
As [scap installation](https://github.com/secdev/scapy#installation) mentioned, there are some depency packages need be installed in Windows environment.

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/issues/1819

We're super slow to release versions...

**Comment by rainmanwy** [comment]
Thanks @gpotter2 for the information.
