### ISSUE TITLE
AttributeError: _name

### ISSUE THREAD

**Issue by marauderlabs** [rainmanwy/robotframework-ScapyLibrary#5]
```
[ ERROR ] Error in file '/home/ubuntu/development/testcases/test.robot': Initializing test library 'ScapyLibrary' with no arguments failed: AttributeError: _name
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotframework_ScapyLibrary-devel-py2.7.egg/ScapyLibrary/__init__.py", line 20, in __init__
    _base.__init__(self)
  File "/usr/local/lib/python2.7/dist-packages/robotframework_ScapyLibrary-devel-py2.7.egg/ScapyLibrary/keywords/layers.py", line 16, in __init__
    self._init_layers()
  File "/usr/local/lib/python2.7/dist-packages/robotframework_ScapyLibrary-devel-py2.7.egg/ScapyLibrary/keywords/layers.py", line 78, in _init_layers
    if protocol._name is None:
  File "/usr/local/lib/python2.7/dist-packages/scapy/base_classes.py", line 192, in __getattr__
    raise AttributeError(attr)

```

**Comment by rainmanwy** [comment]
@marauderlabs , could have a try the latest version of scapy and scapylibrary?
